# Site settings
title: Bedrock Labs
email: jlewis@bedrocklabs.io
url: https://bedrocklabs.io
#description: "Working at the intersection of climate and technology"
description: Incubating technology for climate

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: https://bedrocklabs.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Bedrock_Labs

# Build settings
markdown: kramdown
permalink: pretty
